In [1]:
import soccerdata as sd
import pandas as pd
# set pandas dispaly options
pd.set_option('display.max_columns', None)

[03/19/24 19:40:55] INFO     No custom team name replacements found. You can configure these in       ]8;id=727829;file://c:\Users\mibam\Documents\GitHub\player-role-identification\.venv\Lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=354757;file://c:\Users\mibam\Documents\GitHub\player-role-identification\.venv\Lib\site-packages\soccerdata\_config.py#87\87]8;;\
                             C:\Users\mibam\soccerdata\config\teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=151624;file://c:\Users\mibam\Documents\GitHub\player-role-identification\.venv\Lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=262793;file://c:\Users\mibam\Documents\GitHub\player-role-identification\.venv\Lib\site-packages\soccerdata\_config.py#177\177]8;;\
                             C:\Users\mibam\soccerdata\config\league_dict.json.

In [7]:
fbref = sd.FBref('ENG-Premier League',seasons=["2017-18"],no_cache=True)

[03/19/24 20:05:57] INFO     Saving cached data to C:\Users\mibam\soccerdata\data\FBref               ]8;id=437346;file://c:\Users\mibam\Documents\GitHub\player-role-identification\.venv\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=896190;file://c:\Users\mibam\Documents\GitHub\player-role-identification\.venv\Lib\site-packages\soccerdata\_common.py#91\91]8;;\

In [17]:
meta_cols = ["season","team","player","nation","pos","age"]

In [18]:
pl_table_shooting = fbref.read_player_season_stats(stat_type='shooting')
pl_table_shooting = pl_table_shooting.reset_index()
pl_table_shooting.columns = [' '.join(col).strip() for col in pl_table_shooting.columns.values]
pl_table_shooting = pl_table_shooting[meta_cols+["Standard Gls","Standard Sh","Standard SoT%","Standard Sh/90","Standard SoT/90","Standard G/Sh","Standard G/SoT","Standard Dist",
                                                 "Standard FK","Standard PK","Standard PKatt","Expected xG","Expected npxG","Expected npxG/Sh","Expected G-xG","Expected np:G-xG"]]
pl_table_shooting.head()

,season,team,player,nation,pos,age,Standard Gls,Standard Sh,Standard SoT%,Standard Sh/90,Standard SoT/90,Standard G/Sh,Standard G/SoT,Standard Dist,Standard FK,Standard PK,Standard PKatt,Expected xG,Expected npxG,Expected npxG/Sh,Expected G-xG,Expected np:G-xG
0,1718,Arsenal,Aaron Ramsey,WAL,MF,26,7,56,44.6,2.73,1.22,0.13,0.28,16.6,0,0,0,6.1,6.1,0.11,0.9,0.9
1,1718,Arsenal,Ainsley Maitland-Niles,ENG,"DF,MF",19,0,5,0.0,0.49,0.0,0.0,<NA>,20.9,0,0,0,0.2,0.2,0.05,-0.2,-0.2
2,1718,Arsenal,Alex Iwobi,NGA,"MF,FW",21,3,45,48.9,2.21,1.08,0.07,0.14,18.4,0,0,0,3.9,3.9,0.09,-0.9,-0.9
3,1718,Arsenal,Alex Oxlade-Chamberlain,ENG,DF,23,0,9,22.2,3.36,0.75,0.0,0.0,25.3,0,0,0,0.3,0.3,0.03,-0.3,-0.3
4,1718,Arsenal,Alexandre Lacazette,FRA,FW,26,14,66,48.5,2.7,1.31,0.18,0.38,13.6,0,2,2,13.7,12.1,0.18,0.3,-0.1

In [19]:
# Get premier leagure table - passing
pl_table_passing = fbref.read_player_season_stats(stat_type='passing')
pl_table_passing = pl_table_passing.reset_index()
pl_table_passing.columns = [' '.join(col).strip() for col in pl_table_passing.columns.values]
pl_table_passing = pl_table_passing[meta_cols+["Total Cmp","Total Att","Total Cmp%","Total TotDist","Total PrgDist","Short Cmp","Short Att","Short Cmp%","Medium Cmp","Medium Att","Medium Cmp%","Long Cmp","Long Att","Long Cmp%","Ast","xAG","Expected xA","Expected A-xAG","KP","1/3","PrgP","CrsPA"]]
pl_table_passing.head()

,season,team,player,nation,pos,age,Total Cmp,Total Att,Total Cmp%,Total TotDist,Total PrgDist,Short Cmp,Short Att,Short Cmp%,Medium Cmp,Medium Att,Medium Cmp%,Long Cmp,Long Att,Long Cmp%,Ast,xAG,Expected xA,Expected A-xAG,KP,1/3,PrgP,CrsPA
0,1718,Arsenal,Aaron Ramsey,WAL,MF,26,1065,1277,83.4,16341,4329,556,627,88.7,390,457,85.3,69,97,71.1,8,5.4,5.3,2.6,28,102,134,3
1,1718,Arsenal,Ainsley Maitland-Niles,ENG,"DF,MF",19,530,640,82.8,8182,2475,290,321,90.3,178,215,82.8,42,59,71.2,0,0.9,1.4,-0.9,8,37,35,4
2,1718,Arsenal,Alex Iwobi,NGA,"MF,FW",21,997,1171,85.1,14645,3786,587,636,92.3,321,379,84.7,53,78,67.9,5,3.5,3.6,1.5,36,93,138,0
3,1718,Arsenal,Alex Oxlade-Chamberlain,ENG,DF,23,124,158,78.5,2464,689,53,58,91.4,48,57,84.2,23,33,69.7,0,0.5,0.6,-0.5,5,12,16,3
4,1718,Arsenal,Alexandre Lacazette,FRA,FW,26,558,744,75.0,6693,1185,369,450,82.0,120,170,70.6,13,25,52.0,4,4.4,4.0,-0.4,36,18,59,3

In [20]:
pl_table_passing_types = fbref.read_player_season_stats(stat_type='passing_types')
pl_table_passing_types = pl_table_passing_types.reset_index()
pl_table_passing_types.columns = [' '.join(col).strip() for col in pl_table_passing_types.columns.values]
pl_table_passing_types = pl_table_passing_types[meta_cols+["Pass Types Live","Pass Types Dead","Pass Types FK","Pass Types TB","Pass Types Sw","Pass Types Crs","Pass Types CK","Corner Kicks In","Corner Kicks Out","Corner Kicks Str","Outcomes Cmp","Outcomes Off","Outcomes Blocks"]]
pl_table_passing_types.head()

,season,team,player,nation,pos,age,Pass Types Live,Pass Types Dead,Pass Types FK,Pass Types TB,Pass Types Sw,Pass Types Crs,Pass Types CK,Corner Kicks In,Corner Kicks Out,Corner Kicks Str,Outcomes Cmp,Outcomes Off,Outcomes Blocks
0,1718,Arsenal,Aaron Ramsey,WAL,MF,26,1236,32,20,10,12,17,0,0,0,0,1065,9,24
1,1718,Arsenal,Ainsley Maitland-Niles,ENG,"DF,MF",19,550,87,6,0,3,20,0,0,0,0,530,3,18
2,1718,Arsenal,Alex Iwobi,NGA,"MF,FW",21,1151,17,3,12,5,20,1,0,1,0,997,3,27
3,1718,Arsenal,Alex Oxlade-Chamberlain,ENG,DF,23,136,20,3,0,3,16,0,0,0,0,124,2,5
4,1718,Arsenal,Alexandre Lacazette,FRA,FW,26,691,48,0,9,1,16,0,0,0,0,558,5,21

In [21]:
# Get premier league table - goal_shot_creation
pl_table_goal_shot_creation = fbref.read_player_season_stats(stat_type='goal_shot_creation')
pl_table_goal_shot_creation = pl_table_goal_shot_creation.reset_index()
pl_table_goal_shot_creation.columns = [' '.join(col).strip() for col in pl_table_goal_shot_creation.columns.values]
pl_table_goal_shot_creation = pl_table_goal_shot_creation[meta_cols+["SCA SCA90","SCA Types PassLive","SCA Types PassDead","SCA Types TO","SCA Types Sh","SCA Types Fld","SCA Types Def","GCA GCA90","GCA Types PassLive","GCA Types PassDead","GCA Types TO","GCA Types Sh","GCA Types Fld","GCA Types Def"]]
pl_table_goal_shot_creation.head()

,season,team,player,nation,pos,age,SCA SCA90,SCA Types PassLive,SCA Types PassDead,SCA Types TO,SCA Types Sh,SCA Types Fld,SCA Types Def,GCA GCA90,GCA Types PassLive,GCA Types PassDead,GCA Types TO,GCA Types Sh,GCA Types Fld,GCA Types Def
0,1718,Arsenal,Aaron Ramsey,WAL,MF,26,3.07,53,0,4,3,3,0,0.63,10,0,1,0,2,0
1,1718,Arsenal,Ainsley Maitland-Niles,ENG,"DF,MF",19,1.77,14,0,4,0,0,0,0.0,0,0,0,0,0,0
2,1718,Arsenal,Alex Iwobi,NGA,"MF,FW",21,4.03,70,1,5,4,2,0,0.59,11,0,0,1,0,0
3,1718,Arsenal,Alex Oxlade-Chamberlain,ENG,DF,23,4.85,9,1,1,1,0,1,0.0,0,0,0,0,0,0
4,1718,Arsenal,Alexandre Lacazette,FRA,FW,26,3.88,59,0,13,12,10,1,0.53,7,0,0,4,1,1

In [22]:
# Get premier league table - defense
pl_table_defense = fbref.read_player_season_stats(stat_type='defense')
pl_table_defense = pl_table_defense.reset_index()
pl_table_defense.columns = [' '.join(col).strip() for col in pl_table_defense.columns.values]
pl_table_defense = pl_table_defense[meta_cols+["Tackles Tkl","Tackles TklW","Tackles Def 3rd","Tackles Mid 3rd","Tackles Att 3rd",
                                               "Challenges Tkl","Challenges Att","Challenges Tkl%","Challenges Lost",
                                               "Blocks Blocks","Blocks Sh","Blocks Pass","Int","Tkl+Int","Clr","Err"]]
pl_table_defense.head()

,season,team,player,nation,pos,age,Tackles Tkl,Tackles TklW,Tackles Def 3rd,Tackles Mid 3rd,Tackles Att 3rd,Challenges Tkl,Challenges Att,Challenges Tkl%,Challenges Lost,Blocks Blocks,Blocks Sh,Blocks Pass,Int,Tkl+Int,Clr,Err
0,1718,Arsenal,Aaron Ramsey,WAL,MF,26,35,27,18,17,0,8,44,18.2,36,14,3,11,24,59,6,1
1,1718,Arsenal,Ainsley Maitland-Niles,ENG,"DF,MF",19,25,17,12,7,6,14,31,45.2,17,15,1,14,12,37,35,2
2,1718,Arsenal,Alex Iwobi,NGA,"MF,FW",21,19,15,8,8,3,5,18,27.8,13,19,1,18,7,26,10,1
3,1718,Arsenal,Alex Oxlade-Chamberlain,ENG,DF,23,5,3,2,2,1,2,3,66.7,1,5,2,3,6,11,8,0
4,1718,Arsenal,Alexandre Lacazette,FRA,FW,26,24,17,6,11,7,4,27,14.8,23,19,3,16,7,31,5,0

In [23]:
# Get premier league table - possession
pl_table_possession = fbref.read_player_season_stats(stat_type='possession')
pl_table_possession = pl_table_possession.reset_index()
pl_table_possession.columns = [' '.join(col).strip() for col in pl_table_possession.columns.values]
pl_table_possession = pl_table_possession[meta_cols+["Touches Touches","Touches Def Pen","Touches Def 3rd","Touches Mid 3rd","Touches Att 3rd",
                                                     "Touches Att Pen","Touches Live","Take-Ons Att","Take-Ons Succ","Take-Ons Succ%","Take-Ons Tkld","Take-Ons Tkld%",
                                                     "Carries Carries","Carries TotDist","Carries PrgDist","Carries PrgC","Carries 1/3","Carries CPA","Carries Mis","Carries Dis","Receiving Rec","Receiving PrgR"]]
pl_table_possession.head()

,season,team,player,nation,pos,age,Touches Touches,Touches Def Pen,Touches Def 3rd,Touches Mid 3rd,Touches Att 3rd,Touches Att Pen,Touches Live,Take-Ons Att,Take-Ons Succ,Take-Ons Succ%,Take-Ons Tkld,Take-Ons Tkld%,Carries Carries,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR
0,1718,Arsenal,Aaron Ramsey,WAL,MF,26,1480,16,174,770,552,91,1480,36,29,80.6,7,19.4,1082,5745,2709,61,54,18,49,37,1214,161
1,1718,Arsenal,Ainsley Maitland-Niles,ENG,"DF,MF",19,762,36,245,313,210,19,762,25,20,80.0,5,20.0,425,1881,937,21,18,5,18,14,478,58
2,1718,Arsenal,Alex Iwobi,NGA,"MF,FW",21,1358,16,146,604,627,80,1358,52,36,69.2,16,30.8,1058,6230,3418,93,80,25,42,31,1131,146
3,1718,Arsenal,Alex Oxlade-Chamberlain,ENG,DF,23,203,8,43,85,85,4,203,21,17,81.0,4,19.0,125,1178,667,19,18,5,5,4,125,21
4,1718,Arsenal,Alexandre Lacazette,FRA,FW,26,980,8,58,308,620,173,978,45,33,73.3,12,26.7,621,2501,906,39,12,27,62,50,756,233

In [24]:
# Get premier league table - playing_time
pl_table_playing_time = fbref.read_player_season_stats(stat_type='playing_time')
pl_table_playing_time = pl_table_playing_time.reset_index()
pl_table_playing_time.columns = [' '.join(col).strip() for col in pl_table_playing_time.columns.values]
pl_table_playing_time = pl_table_playing_time[meta_cols+["Playing Time Mn/MP","Playing Time Min%","Playing Time 90s",
                                                         "Team Success PPM","Team Success onG","Team Success onGA","Team Success +/-","Team Success +/-90",
                                                         "Team Success On-Off","Team Success (xG) onxG","Team Success (xG) onxGA","Team Success (xG) xG+/-","Team Success (xG) xG+/-90",
                                                         "Team Success (xG) On-Off"]]
pl_table_playing_time.head()

,season,team,player,nation,pos,age,Playing Time Mn/MP,Playing Time Min%,Playing Time 90s,Team Success PPM,Team Success onG,Team Success onGA,Team Success +/-,Team Success +/-90,Team Success On-Off,Team Success (xG) onxG,Team Success (xG) onxGA,Team Success (xG) xG+/-,Team Success (xG) xG+/-90,Team Success (xG) On-Off
0,1718,Arsenal,Aaron Ramsey,WAL,MF,26,77,54.0,20.5,1.83,42,25,17,0.83,0.49,42.8,23.0,19.8,0.97,0.93
1,1718,Arsenal,Ainsley Maitland-Niles,ENG,"DF,MF",19,61,26.7,10.2,1.67,17,16,1,0.1,-0.69,14.3,14.3,0.0,0.0,-0.74
2,1718,Arsenal,Alex Iwobi,NGA,"MF,FW",21,70,53.5,20.3,1.42,36,26,10,0.49,-0.24,35.6,25.5,10.2,0.5,-0.08
3,1718,Arsenal,Alex Oxlade-Chamberlain,ENG,DF,23,80,7.0,2.7,1.0,4,7,-3,-1.12,-1.86,4.2,4.6,-0.4,-0.14,-0.74
4,1718,Arsenal,Alexandre Lacazette,FRA,FW,26,69,64.4,24.5,1.78,51,28,23,0.94,0.94,46.9,27.4,19.5,0.8,0.72

In [25]:
# Get premier league table - misc
pl_table_misc = fbref.read_player_season_stats(stat_type='misc')
pl_table_misc = pl_table_misc.reset_index()
pl_table_misc.columns = [' '.join(col).strip() for col in pl_table_misc.columns.values]
pl_table_misc = pl_table_misc[meta_cols+["Performance CrdY","Performance CrdR","Performance 2CrdY","Performance Fld",
                                         "Performance Off","Performance Crs","Performance Int","Performance TklW","Performance PKwon","Performance PKcon",
                                         "Aerial Duels Won","Aerial Duels Lost","Aerial Duels Won%"]]
pl_table_misc.head()

,season,team,player,nation,pos,age,Performance CrdY,Performance CrdR,Performance 2CrdY,Performance Fld,Performance Off,Performance Crs,Performance Int,Performance TklW,Performance PKwon,Performance PKcon,Aerial Duels Won,Aerial Duels Lost,Aerial Duels Won%
0,1718,Arsenal,Aaron Ramsey,WAL,MF,26,0,0,0,33,0,17,24,27,2,0,10,15,40.0
1,1718,Arsenal,Ainsley Maitland-Niles,ENG,"DF,MF",19,1,0,0,5,0,20,12,17,0,1,6,14,30.0
2,1718,Arsenal,Alex Iwobi,NGA,"MF,FW",21,1,0,0,12,1,20,7,15,0,0,3,14,17.6
3,1718,Arsenal,Alex Oxlade-Chamberlain,ENG,DF,23,0,0,0,1,1,16,6,3,0,0,4,6,40.0
4,1718,Arsenal,Alexandre Lacazette,FRA,FW,26,1,0,0,28,23,16,7,17,1,0,29,60,32.6

In [26]:
dfs = [pl_table_shooting, pl_table_passing, pl_table_passing_types, pl_table_goal_shot_creation, pl_table_defense, pl_table_possession, pl_table_playing_time, pl_table_misc]
pl_table_all = pd.concat([df.set_index(meta_cols) for df in dfs], axis=1, join="inner").reset_index()
pl_table_all.head()

,season,team,player,nation,pos,age,Standard Gls,Standard Sh,Standard SoT%,Standard Sh/90,Standard SoT/90,Standard G/Sh,Standard G/SoT,Standard Dist,Standard FK,Standard PK,Standard PKatt,Expected xG,Expected npxG,Expected npxG/Sh,Expected G-xG,Expected np:G-xG,Total Cmp,Total Att,Total Cmp%,Total TotDist,Total PrgDist,Short Cmp,Short Att,Short Cmp%,Medium Cmp,Medium Att,Medium Cmp%,Long Cmp,Long Att,Long Cmp%,Ast,xAG,Expected xA,Expected A-xAG,KP,1/3,PrgP,CrsPA,Pass Types Live,Pass Types Dead,Pass Types FK,Pass Types TB,Pass Types Sw,Pass Types Crs,Pass Types CK,Corner Kicks In,Corner Kicks Out,Corner Kicks Str,Outcomes Cmp,Outcomes Off,Outcomes Blocks,SCA SCA90,SCA Types PassLive,SCA Types PassDead,SCA Types TO,SCA Types Sh,SCA Types Fld,SCA Types Def,GCA GCA90,GCA Types PassLive,GCA Types PassDead,GCA Types TO,GCA Types Sh,GCA Types Fld,GCA Types Def,Tackles Tkl,Tackles TklW,Tackles Def 3rd,Tackles Mid 3rd,Tackles Att 3rd,Challenges Tkl,Challenges Att,Challenges Tkl%,Challenges Lost,Blocks Blocks,Blocks Sh,Blocks Pass,Int,Tkl+Int,Clr,Err,Touches Touches,Touches Def Pen,Touches Def 3rd,Touches Mid 3rd,Touches Att 3rd,Touches Att Pen,Touches Live,Take-Ons Att,Take-Ons Succ,Take-Ons Succ%,Take-Ons Tkld,Take-Ons Tkld%,Carries Carries,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR,Playing Time Mn/MP,Playing Time Min%,Playing Time 90s,Team Success PPM,Team Success onG,Team Success onGA,Team Success +/-,Team Success +/-90,Team Success On-Off,Team Success (xG) onxG,Team Success (xG) onxGA,Team Success (xG) xG+/-,Team Success (xG) xG+/-90,Team Success (xG) On-Off,Performance CrdY,Performance CrdR,Performance 2CrdY,Performance Fld,Performance Off,Performance Crs,Performance Int,Performance TklW,Performance PKwon,Performance PKcon,Aerial Duels Won,Aerial Duels Lost,Aerial Duels Won%
0,1718,Arsenal,Aaron Ramsey,WAL,MF,26,7,56,44.6,2.73,1.22,0.13,0.28,16.6,0,0,0,6.1,6.1,0.11,0.9,0.9,1065,1277,83.4,16341,4329,556,627,88.7,390,457,85.3,69,97,71.1,8,5.4,5.3,2.6,28,102,134,3,1236,32,20,10,12,17,0,0,0,0,1065,9,24,3.07,53,0,4,3,3,0,0.63,10,0,1,0,2,0,35,27,18,17,0,8,44,18.2,36,14,3,11,24,59,6,1,1480,16,174,770,552,91,1480,36,29,80.6,7,19.4,1082,5745,2709,61,54,18,49,37,1214,161,77,54.0,20.5,1.83,42,25,17,0.83,0.49,42.8,23.0,19.8,0.97,0.93,0,0,0,33,0,17,24,27,2,0,10,15,40.0
1,1718,Arsenal,Ainsley Maitland-Niles,ENG,"DF,MF",19,0,5,0.0,0.49,0.0,0.0,<NA>,20.9,0,0,0,0.2,0.2,0.05,-0.2,-0.2,530,640,82.8,8182,2475,290,321,90.3,178,215,82.8,42,59,71.2,0,0.9,1.4,-0.9,8,37,35,4,550,87,6,0,3,20,0,0,0,0,530,3,18,1.77,14,0,4,0,0,0,0.0,0,0,0,0,0,0,25,17,12,7,6,14,31,45.2,17,15,1,14,12,37,35,2,762,36,245,313,210,19,762,25,20,80.0,5,20.0,425,1881,937,21,18,5,18,14,478,58,61,26.7,10.2,1.67,17,16,1,0.1,-0.69,14.3,14.3,0.0,0.0,-0.74,1,0,0,5,0,20,12,17,0,1,6,14,30.0
2,1718,Arsenal,Alex Iwobi,NGA,"MF,FW",21,3,45,48.9,2.21,1.08,0.07,0.14,18.4,0,0,0,3.9,3.9,0.09,-0.9,-0.9,997,1171,85.1,14645,3786,587,636,92.3,321,379,84.7,53,78,67.9,5,3.5,3.6,1.5,36,93,138,0,1151,17,3,12,5,20,1,0,1,0,997,3,27,4.03,70,1,5,4,2,0,0.59,11,0,0,1,0,0,19,15,8,8,3,5,18,27.8,13,19,1,18,7,26,10,1,1358,16,146,604,627,80,1358,52,36,69.2,16,30.8,1058,6230,3418,93,80,25,42,31,1131,146,70,53.5,20.3,1.42,36,26,10,0.49,-0.24,35.6,25.5,10.2,0.5,-0.08,1,0,0,12,1,20,7,15,0,0,3,14,17.6
3,1718,Arsenal,Alex Oxlade-Chamberlain,ENG,DF,23,0,9,22.2,3.36,0.75,0.0,0.0,25.3,0,0,0,0.3,0.3,0.03,-0.3,-0.3,124,158,78.5,2464,689,53,58,91.4,48,57,84.2,23,33,69.7,0,0.5,0.6,-0.5,5,12,16,3,136,20,3,0,3,16,0,0,0,0,124,2,5,4.85,9,1,1,1,0,1,0.0,0,0,0,0,0,0,5,3,2,2,1,2,3,66.7,1,5,2,3,6,11,8,0,203,8,43,85,85,4,203,21,17,81.0,4,19.0,125,1178,667,19,18,5,5,4,125,21,80,7.0,2.7,1.0,4,7,-3,-1.12,-1.86,4.2,4.6,-0.4,-0.14,-0.74,0,0,0,1,1,16,6,3,0,0,4,6,40.0
4,1718,Arsenal,Alexandre Lacazette,FRA,FW,26,14,66,48.5,2.7,1.31,0.18,0.38,13.6,0,2,2,13.7,12.1,0.18,0.3,-0.1,558,744,75.0,6693,1185,369,450,82.0,120,170,70.6,13,25,52.0,4,4.4,4.0,-0.4,36,18,59,3,691,48,0,9,1,16,0,0,0,0,558,5,21,3.88,59,0,13,12,10,1,0.53,7,0,0,4,1,1,24,17,6,11,7,4,27,14.8,23,19,3,16,7,31,5,0,980,8,58,308,620,173,978,45,33,73.3,12,26.7,621,2501,906,39,12,27,62,50,756,233,69,64.4,24.5,1.78,51,28,23,0.94,0.94,46.9,27.4,19.5,0.8,0.72,1,0,0,28,23,16,7,17,1,0,29,60,32.6

In [27]:
pl_table_all.to_csv("./data/FBref/pl_table_2017_18.csv", index=False)

In [30]:
understat = sd.Understat(['ENG-Premier League'],seasons=['2017-2018'],no_cache=True)
understat_shots = understat.read_shot_events()
understat_shots = understat_shots.reset_index()
understat_shots.head()

[03/19/24 20:37:02] INFO     Saving cached data to C:\Users\mibam\soccerdata\data\Understat           ]8;id=305081;file://c:\Users\mibam\Documents\GitHub\player-role-identification\.venv\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=40607;file://c:\Users\mibam\Documents\GitHub\player-role-identification\.venv\Lib\site-packages\soccerdata\_common.py#91\91]8;;\

,league,season,game,team,player,league_id,season_id,game_id,date,shot_id,team_id,player_id,assist_player_id,assist_player,xg,location_x,location_y,minute,body_part,situation,result
0,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester,Arsenal,Aaron Ramsey,1,2017,7119,2017-08-11 19:45:00,158153,83,504,175801,Alexandre Lacazette,0.389223,0.923,0.509,67,<NA>,Open Play,Missed Shot
1,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester,Arsenal,Aaron Ramsey,1,2017,7119,2017-08-11 19:45:00,158161,83,504,175798,Granit Xhaka,0.017764,0.929,0.634,80,<NA>,From Corner,Missed Shot
2,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester,Arsenal,Aaron Ramsey,1,2017,7119,2017-08-11 19:45:00,158162,83,504,175798,Granit Xhaka,0.058752,0.94,0.371,82,Right Foot,From Corner,Goal
3,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester,Arsenal,Aaron Ramsey,1,2017,7119,2017-08-11 19:45:00,158165,83,504,175798,Granit Xhaka,0.027025,0.744,0.421,94,Right Foot,Open Play,Missed Shot
4,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester,Arsenal,Alex Oxlade-Chamberlain,1,2017,7119,2017-08-11 19:45:00,158136,83,966,175799,Mesut Özil,0.017942,0.807,0.72,7,Left Foot,Open Play,Missed Shot

In [32]:
understat_shots.body_part.unique()

<StringArray>
[<NA>, 'Right Foot', 'Left Foot']
Length: 3, dtype: string

In [33]:
understat_aggr = understat_shots[["player","location_x","location_y","minute"]].groupby("player").mean().reset_index()
understat_aggr.head()

              player  location_x  location_y     minute
0    Aaron Cresswell    0.757333    0.633762  44.238095
1       Aaron Lennon    0.861643    0.468357  45.642857
2         Aaron Mooy    0.809517    0.494241  49.931034
3       Aaron Ramsey    0.861196    0.506518  49.267857
4  Abdelhamid Sabiri       0.861      0.4928       51.0

In [34]:
understat_aggr.to_csv("./data/Understat/understat_aggr_2017_18.csv", index=False)

In [31]:
# dummify shot body_part variable
#understat_shots = pd.get_dummies(understat_shots, columns=["body_part"], prefix="body_part")
#pd.get_dummies(understat_shots, columns=["body_part"], prefix="body_part")

,league,season,game,team,player,league_id,season_id,game_id,date,shot_id,team_id,player_id,assist_player_id,assist_player,xg,location_x,location_y,minute,situation,result,body_part_Left Foot,body_part_Right Foot
0,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester,Arsenal,Aaron Ramsey,1,2017,7119,2017-08-11 19:45:00,158153,83,504,175801,Alexandre Lacazette,0.389223,0.923,0.509,67,Open Play,Missed Shot,False,False
1,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester,Arsenal,Aaron Ramsey,1,2017,7119,2017-08-11 19:45:00,158161,83,504,175798,Granit Xhaka,0.017764,0.929,0.634,80,From Corner,Missed Shot,False,False
2,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester,Arsenal,Aaron Ramsey,1,2017,7119,2017-08-11 19:45:00,158162,83,504,175798,Granit Xhaka,0.058752,0.94,0.371,82,From Corner,Goal,False,True
3,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester,Arsenal,Aaron Ramsey,1,2017,7119,2017-08-11 19:45:00,158165,83,504,175798,Granit Xhaka,0.027025,0.744,0.421,94,Open Play,Missed Shot,False,True
4,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester,Arsenal,Alex Oxlade-Chamberlain,1,2017,7119,2017-08-11 19:45:00,158136,83,966,175799,Mesut Özil,0.017942,0.807,0.72,7,Open Play,Missed Shot,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9282,ENG-Premier League,1718,2018-05-13 West Ham-Everton,West Ham,Mark Noble,1,2017,7489,2018-05-13 15:00:00,215634,81,533,240128,Marko Arnautovic,0.489269,0.93,0.575,9,Open Play,Saved Shot,False,True
9283,ENG-Premier League,1718,2018-05-13 West Ham-Everton,West Ham,Marko Arnautovic,1,2017,7489,2018-05-13 15:00:00,215633,81,865,<NA>,<NA>,0.084131,0.883,0.571,9,Open Play,Blocked Shot,True,False
9284,ENG-Premier League,1718,2018-05-13 West Ham-Everton,West Ham,Marko Arnautovic,1,2017,7489,2018-05-13 15:00:00,215637,81,865,240125,Mark Noble,0.035728,0.859,0.721,30,Open Play,Blocked Shot,False,True
9285,ENG-Premier League,1718,2018-05-13 West Ham-Everton,West Ham,Marko Arnautovic,1,2017,7489,2018-05-13 15:00:00,215647,81,865,240130,Edimilson Fernandes,0.027316,0.787,0.352,62,Open Play,Goal,False,True
9286,ENG-Premier League,1718,2018-05-13 West Ham-Everton,West Ham,Pablo Zabaleta,1,2017,7489,2018-05-13 15:00:00,215652,81,610,240128,Marko Arnautovic,0.146869,0.926,0.439,75,Open Play,Missed Shot,True,False